# SHA hash algorithms.
import hashlib


if __name__ == "__main__":

    print("HashCode Generated by SHA-1 for: ")

    # initializing string
    s1 = "This is a Test"

    res1 = hashlib.sha1(s1.encode())

    # printing the equivalent hexadecimal value.
    print ("The hexadecimal equivalent of SHA1 is : ")

    print (s1 + " : " + res1.hexdigest())