package Hash;

/***
 *
 * @author ozil
 * GitHub : https://github.com/mmsaeed509
 *
 * */

// import Libs
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;


// import encryption class
import Hash.SHA_1;


public class Main {

    public static void main(String[] args) throws NoSuchAlgorithmException {

        String message;
        Scanner read = new Scanner(System.in);

        System.out.println("");
        System.out.println("*********************************");
        System.out.println("*  HashCode Generated by SHA-1  *");
        System.out.println("*********************************");

        while (true){

            System.out.println("Write Message : ");
            message = read.nextLine();

            if (message.equals("stop"))
                break;
            else
                System.out.println("\nThe HashCode Of " + message + "    is  : " + SHA_1.encryptMessage(message));

        }


    }
}
